<script type="application/ld+json">
{ "@context" : "http://schema.org",
  "@type" : "Organization",
  "url" : "<?php echo $this->getBaseUrl(); ?>",
  "logo" : "<?php echo $this->getSkinUrl(Mage::getStoreConfig('design/header/logo_src'));?>",
  "sameAs": "https://www.facebook.com/pages/Deco-Ameublementcom/349930961684561",
  "contactPoint" : [
  {
    "@type" : "ContactPoint",
    "telephone" : "+33-231857575",
    "contactType" : "customer service",
    "contactOption": "TollFree",
    "availableLanguage": "French"
  },
  {
    "@type" : "ContactPoint",
    "telephone" : "+33-631864984",
    "contactType" : "customer service",
    "contactOption": "TollFree",
    "availableLanguage": "French"
  }
  ]
}
</script>
